import { SideNavBar } from "@/components/admin/SideNavBar";
import "../../globals.css";
import TopNavBar from "@/components/admin/TopNavBar";

export const metadata = {
  title: "Shaadi Vyah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="lg:flex">
        <div className="w-1/5 hidden lg:block ">
          <SideNavBar />
        </div>
        <div className="lg:flex flex-col lg:w-4/5">
          <div className="h-16 ">
            <TopNavBar />
          </div>

          <main className="min-h-screen ">
            {children}
          </main>
        </div>
      </div>
    </html>
  );
}
